name: AutoWalls
main: com.jkush321.autowalls.AutoWalls
version: 2.0.0-BETA
authors: [jkush321, Johnn, Not2EXceL, minnymin3]
permissions:
  walls.player:
    description: Player of walls
    default: true
  walls.op:
    description: Operator of walls
    default: op